version: '3'
volumes:
  dfs-db:
  dfs-test-db:
services:
  server:
    image: nginx
    env_file: .env
    volumes:
      - .docker/services/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html/:cached
    ports:
      - 8080:80
    restart: always
    depends_on:
      - php
  php:
    build:
      context: .docker/services/php
    env_file: .env
    restart: always
    volumes:
      - .docker/services/php/logs.ini:/usr/local/etc/php/conf.d/logs.ini
      - .docker/services/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - .:/var/www/html:cached
    depends_on:
      - composer
  composer:
    image: composer
    volumes:
        - .:/app
    command: install
  db:
    image: mysql:5.7.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3366:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: orderingsystem
    volumes:
      - dfs-db:/var/lib/mysql
  test_db:
    image: mysql:5.7.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3367:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: orderingsystem_testing
    volumes:
      - dfs-test-db:/var/lib/mysql
